### ISSUE TITLE
Howto use it

### ISSUE THREAD

**Issue by ouranos6** [cenk1cenk2/softether-vpnsrv#2]
Hi,

I try to use your image with the dnsmasq but it's impossible to make it working.

Here is my attempt, maybe you can explain how to use/start the container.

`docker run -v /opt/dnsmasq.conf:/usr/local/vpnserver/dnsmasq.conf  --privileged --cap-add NET_ADMIN cenk1cenk2/softether-vpnsrv`

Thanks in advance

**Comment by cenk1cenk2** [comment]
I will update readme as soon as possible.

**Comment by cenk1cenk2** [comment]
I updated the readme to my best extend simplified the code for initial-setup process. Hope it will be more helpful, otherwise you can just ask here again.
