### ISSUE TITLE
restart loop, iptables, 10-routing.sh

### ISSUE THREAD

**Issue by SuperHofstad** [cenk1cenk2/softether-vpnsrv#5]
[s6-finish] sending all processes the TERM signal.

[s6-finish] sending all processes the KILL signal and exiting.

[s6-init] making user provided files available at /var/run/s6/etc...exited 0.

[s6-init] ensuring user provided files have correct perms...exited 0.

[fix-attrs.d] applying ownership & permissions fixes...

[fix-attrs.d] done.

[cont-init.d] executing container initialization scripts...

[cont-init.d] 10-routing.sh: executing... 

Creating postrouting rules.

iptables v1.8.3 (legacy): host/network `10.0.0.0.0' not found

Try `iptables -h' or 'iptables --help' for more information.

[cont-init.d] 10-routing.sh: exited 2.

[cont-finish.d] executing container finish scripts...

[cont-finish.d] done.

[s6-finish] waiting for services.

[s6-finish] syncing disks.

[s6-finish] sending all processes the TERM signal.

[s6-finish] sending all processes the KILL signal and exiting.

 

 

 

I checked the code in 10-routing.sh, but to my limited knowledge about linux and network, it looks good.

This is the code it should run:
"iptables -t nat -A POSTROUTING -s ${SRVIPSUBNET:-10.0.0}.0/24 -j MASQUERADE"

Haven't tried on an other server yet, but this is using the unmodified(almost, see pull request) "Deploy via Docker" command set

**Comment by cenk1cenk2** [comment]
Srvipsubnet variable shall not have the last hexadecimal part i will correct it on the readme. 
So it should be like `-e SRVIPSUBNET =10.0.0`
That was a typo on my behalf sorry.
Please try and see if that works.
