### ISSUE TITLE
container not exposing ports correctly?

### ISSUE THREAD

**Issue by SuperHofstad** [cenk1cenk2/softether-vpnsrv#6]
container 1:  portainer, can access outside eth0(ens33) on port 9000 no problem
container 2: softether-vpnsrv, can**not** access outside eth0(ens33), can access it from within, on host(docker host)

host running docker on ubuntu, network is bridged, no firewall.

I.e: can access portainer-container port 9000tcp, cannot access softether-vpnsrv-container on any ports, outside eth0(ens33)

Can confirm in portainer that all ports are assigned.

**Comment by cenk1cenk2** [comment]
![image](https://user-images.githubusercontent.com/26881592/78648920-fe120500-78bc-11ea-971b-d24a83f1ed61.png)
The issue seems to be not reproducible with me on default settings. I preassume you are running this on layer-2 virtual machine?

**Comment by SuperHofstad** [comment]
I will try different docker host os, and on a vps from scratch later today
