### ISSUE TITLE
Why is DnsMasq DHCP server needed

### ISSUE THREAD

**Issue by lonnietc** [cenk1cenk2/softether-vpnsrv#8]
Hello,

I am wondering why DnsMasq DHCP server is needed when the SoftEther Server already provides a DHCP server?

The  DnsMasq DHCP server could be useful from the aspect that I do not think that SoftEther provides this feature when running in Cluster mode from what I have read, but just wanted to get some information from you as to why it was included.

Thanks

**Comment by disaac** [comment]
@lonnietc The SoftEther [SecureNAT](https://www.softether.org/index.php?title=4-docs/1-manual/3._SoftEther_VPN_Server_Manual/3.7_Virtual_NAT_%26_Virtual_DHCP_Servers) support was quite flaky in containers **when I tried it**. I attempted leveraging its SecureNAT and DHCP services and it would eventually bring my connections to a crawl. Using dnsmasq avoided memory and CPU spiking. Additionally I saw ping responses for traffic through the vpn connection going from 10%+ packet loss to 0% once I switched to using dnsmasq.

This was my experience when using [siomiz/softethervpn](https://hub.docker.com/r/siomiz/softethervpn/). Thanks for the awesome solution @cenk1cenk2 works great!

**Comment by cenk1cenk2** [comment]
Thank you @disaac Mr. Daniel.

There are already alternatives without it, but to my experience, it performs much better with dnsmasq acting as the DHCP server both in responsiveness and throughput. 

**The interesting thing is I got no mails from this repo and there are open issues. 

Sorry for responding late.**
