### ISSUE TITLE
tap_soft interface created without specifying netmask

### ISSUE THREAD

**Issue by disaac** [cenk1cenk2/softether-vpnsrv#9]
Currently there is no netmask specified in `ifconfig tap_soft` even though the defaults are using `/24` through out the other configurations. This would prevent properly routing/masquerading any additional networks that may exist in the 10.8.0.0/16 CIDR.

Created [PR#10](https://github.com/cenk1cenk2/softether-vpnsrv/pull/10) to address this. PR allows providing a netmask and defaulting to 255.255.255.0 as is the case for the other configurations such as dnsmasq.conf. It additionally adds the netmask to the ifconfig so the route table is properly set.

**Comment by cenk1cenk2** [comment]
Thank you for this great contrubition. I have not thought this container gets tranction so i just made it for my specific use case. I will merge it as soon as I can.

**Comment by cenk1cenk2** [comment]
I think while we are at it we can also set the IP_START and IP_END, I will also add that.
